/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget { 'monthlyLimit' : number, 'category' : string }
export interface Expense {
  'date' : string,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export interface ExpenseGroup { 'members' : Array<Principal>, 'name' : string }
export interface FinancialSurvey {
  'stressLevel' : bigint,
  'sharedExpenseBehavior' : string,
  'incomeSource' : string,
  'incomeRange' : string,
  'financialHabits' : string,
  'biggestProblem' : string,
  'emergencySavings' : boolean,
}
export interface SharedExpense {
  'splitType' : SplitType,
  'description' : string,
  'groupId' : string,
  'amount' : number,
}
export type SplitType = { 'custom' : Array<[Principal, number]> } |
  { 'equal' : null };
export interface UserProfile {
  'age' : bigint,
  'livingSituation' : string,
  'name' : string,
  'gender' : string,
  'course' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomCategory' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[Expense], undefined>,
  'addMember' : ActorMethod<[string, Principal], undefined>,
  'addSharedExpense' : ActorMethod<
    [string, number, string, SplitType],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, string], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'getBudgets' : ActorMethod<[], Array<Budget>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getGroupExpenses' : ActorMethod<[string], Array<SharedExpense>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSurvey' : ActorMethod<[], [] | [FinancialSurvey]>,
  'getUserGroups' : ActorMethod<[], Array<ExpenseGroup>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markSettlementPaid' : ActorMethod<[string, bigint], undefined>,
  'removeMember' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBudget' : ActorMethod<[string, number], undefined>,
  'submitSurvey' : ActorMethod<[FinancialSurvey], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];