/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Expense = IDL.Record({
  'date' : IDL.Text,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const SplitType = IDL.Variant({
  'custom' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64)),
  'equal' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'livingSituation' : IDL.Text,
  'name' : IDL.Text,
  'gender' : IDL.Text,
  'course' : IDL.Text,
});
export const Budget = IDL.Record({
  'monthlyLimit' : IDL.Float64,
  'category' : IDL.Text,
});
export const SharedExpense = IDL.Record({
  'splitType' : SplitType,
  'description' : IDL.Text,
  'groupId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FinancialSurvey = IDL.Record({
  'stressLevel' : IDL.Nat,
  'sharedExpenseBehavior' : IDL.Text,
  'incomeSource' : IDL.Text,
  'incomeRange' : IDL.Text,
  'financialHabits' : IDL.Text,
  'biggestProblem' : IDL.Text,
  'emergencySavings' : IDL.Bool,
});
export const ExpenseGroup = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomCategory' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func([Expense], [], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addSharedExpense' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, SplitType],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getGroupExpenses' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SharedExpense)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSurvey' : IDL.Func([], [IDL.Opt(FinancialSurvey)], ['query']),
  'getUserGroups' : IDL.Func([], [IDL.Vec(ExpenseGroup)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markSettlementPaid' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'submitSurvey' : IDL.Func([FinancialSurvey], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Expense = IDL.Record({
    'date' : IDL.Text,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const SplitType = IDL.Variant({
    'custom' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64)),
    'equal' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'livingSituation' : IDL.Text,
    'name' : IDL.Text,
    'gender' : IDL.Text,
    'course' : IDL.Text,
  });
  const Budget = IDL.Record({
    'monthlyLimit' : IDL.Float64,
    'category' : IDL.Text,
  });
  const SharedExpense = IDL.Record({
    'splitType' : SplitType,
    'description' : IDL.Text,
    'groupId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FinancialSurvey = IDL.Record({
    'stressLevel' : IDL.Nat,
    'sharedExpenseBehavior' : IDL.Text,
    'incomeSource' : IDL.Text,
    'incomeRange' : IDL.Text,
    'financialHabits' : IDL.Text,
    'biggestProblem' : IDL.Text,
    'emergencySavings' : IDL.Bool,
  });
  const ExpenseGroup = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomCategory' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func([Expense], [], []),
    'addMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addSharedExpense' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, SplitType],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getGroupExpenses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SharedExpense)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSurvey' : IDL.Func([], [IDL.Opt(FinancialSurvey)], ['query']),
    'getUserGroups' : IDL.Func([], [IDL.Vec(ExpenseGroup)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markSettlementPaid' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'submitSurvey' : IDL.Func([FinancialSurvey], [], []),
  });
};

export const init = ({ IDL }) => { return []; };